permalink: /:categories/:title.html
url: "http://keco.github.io/"
full_name: "Keco"
first_name: "Keco"
last_name: "Yuan"
blog_title: "Keco's Blog "
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "pasinduland"
copyright_year: "2015"
google_analytics_code: ""
aboutme: "穿正装的ITer，科技创新可造未来"
twitter: "无"
github: "keco"
facebook: "无"
linkined_url: ""
